version: '2' 
services:
  recastfrontend:
    build: .
    command: 'recast-frontend server --config carinaconfig.takeit_yml'
    ports:
     - "5000:5000"
    links:
     - postgres
     - redis
     # - api
     
  # api:
  #   image: cbora/recastrestapi:0.1
  #   volumes:
  #    - configvolume:/recast-rest-api/recastrestapi/resources/defaultconfig.yaml
  #   ports:
  #    - "6000:5000"
  #   links:
  #    - postgres

  data:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql
    command: "tail -f /dev/null"

  postgres:
    restart: always
    image: postgres:latest
    volumes_from:
      - data
  redis:
    restart: always
    image: redis:latest

  