recastfrontend:
  build: .
  ports:
   - "5000:5000"
  volumes:
   - ./recastfrontend:/recast-newfrontend/recastfrontend
   - ./config.yaml:/recast-newfrontend/recastfrontend/resources/defaultconfig.yaml
  links:
   - db
   - cache
   - celery

db:
  image: postgres
  
celery:
  image: celery

cache:
  image: redis
  ports:
   - "6379:6379"

api:
  image: cbora/recastrestapi:0.1
  volumes:
   - ./config.yaml:/recast-rest-api/recastrestapi/resources/defaultconfig.yaml
  ports:
   - "6000:5000"
  
es:
  image: elasticsearch
  ports:
   - "9200:9200"
  