ORCID_APPID: 'ORCID_APPID'
ORCID_REDIRECT_URI: 'ORCID_REDIRECT_URI'
ORCID_SECRET: 'ORCID_SECRET'
HOSTNAME: 'localhost'
CELERYAPP: 'recastfrontend.celeryapp'
FLASKCONFIG: 'recastfrontend.flaskconfig'
DBPATH: 'database.db'